// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	di "github.com/kuetix/container"
	"github.com/kuetix/engine/engine/defines"
	"github.com/kuetix/engine/engine/workflow"
	transitionsCli "github.com/kuetix/std-cli/modules/cli/transitions"
)

func init() {
	di.Boot()
	di.DependencyInjection["cli"] = func(name string) {
		di.ToResolve(defines.TransitionPrefix+"cli", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "cli", Impl: transitionsCli.NewCliTransition()}
		})
		di.ToResolve(defines.TransitionPrefix+"cli"+"/"+"command", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "command", Impl: transitionsCli.NewCommandTransition()}
		})
		di.ToResolve(defines.TransitionPrefix+"cli"+"/"+"help", func() interface{} {
			return workflow.ServiceTransitionMapping{ServiceName: name, Name: "help", Impl: transitionsCli.NewHelpTransition()}
		})
	}
}
