// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	"github.com/kuetix/engine/boot"
	"github.com/kuetix/engine/engine/domain/interfaces"
)

func init() {
	boot.AddMetaFunctionCache(map[string]map[string]map[string]interfaces.FunctionMetadata{
		"cli": {
			"command": {
				"Echo": {
					GoModule:    "github.com/kuetix/std-cli",
					ModulePath:  "modules",
					FilePath:    "modules/cli/transitions/command.go",
					Namespace:   "command",
					Class:       "cli",
					Name:        "Echo",
					NumIn:       4,
					NumOut:      1,
					ArgTypes:    []string{"string", "map[string]interface{}", "*flag.FlagSet", "map[string]interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"command", "config", "flagSet", "flags"},
					ReturnNames: []string{"r"},
				},
			},
			"help": {
				"Help": {
					GoModule:    "github.com/kuetix/std-cli",
					ModulePath:  "modules",
					FilePath:    "modules/cli/transitions/help.go",
					Namespace:   "help",
					Class:       "cli",
					Name:        "Help",
					NumIn:       7,
					NumOut:      1,
					ArgTypes:    []string{"string", "map[string]interface{}", "map[string]interface{}", "map[string]interface{}", "map[string]interface{}", "*flag.FlagSet", "map[string]interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"command", "commands", "requestedCommand", "commandConfig", "config", "flagSet", "flags"},
					ReturnNames: []string{"r"},
				},
			},
			"cli": {
				"InitCommand": {
					GoModule:    "github.com/kuetix/std-cli",
					ModulePath:  "modules",
					FilePath:    "modules/cli/transitions/cli.go",
					Namespace:   "cli",
					Class:       "cli",
					Name:        "InitCommand",
					NumIn:       2,
					NumOut:      1,
					ArgTypes:    []string{"string", "map[string]interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"command", "flags"},
					ReturnNames: []string{"r"},
				},
				"RegisterCommands": {
					GoModule:    "github.com/kuetix/std-cli",
					ModulePath:  "modules",
					FilePath:    "modules/cli/transitions/cli.go",
					Namespace:   "cli",
					Class:       "cli",
					Name:        "RegisterCommands",
					NumIn:       6,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "string", "string", "string", "map[string]interface{}"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"modulesPath", "workflowsPath", "version", "buildTime", "defaultCommand", "groups"},
					ReturnNames: []string{"r"},
				},
				"UnregisteredCommand": {
					GoModule:    "github.com/kuetix/std-cli",
					ModulePath:  "modules",
					FilePath:    "modules/cli/transitions/cli.go",
					Namespace:   "cli",
					Class:       "cli",
					Name:        "UnregisteredCommand",
					NumIn:       1,
					NumOut:      1,
					ArgTypes:    []string{"any"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"value"},
					ReturnNames: []string{"r"},
				},
				"WorkflowExecutor": {
					GoModule:    "github.com/kuetix/std-cli",
					ModulePath:  "modules",
					FilePath:    "modules/cli/transitions/cli.go",
					Namespace:   "cli",
					Class:       "cli",
					Name:        "WorkflowExecutor",
					NumIn:       7,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "map[string]interface{}", "[]string", "bool", "bool", "bool"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"command", "workflowPath", "config", "args", "verbose", "debug", "quiet"},
					ReturnNames: []string{"result"},
				},
			},
		},
	})
}
