// Code generated by kueinit. DO NOT EDIT.
package modules

import (
	"github.com/kuetix/engine/boot"
	"github.com/kuetix/engine/pkg/domain/interfaces"
)

func init() {
	boot.AddMetaFunctionCache(map[string]map[string]map[string]interfaces.FunctionMetadata{
		"cli": {
			"cli": {
				"RegisterCommands": {
					Name:        "RegisterCommands",
					NumIn:       5,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "string", "string", "map[string]*ast.InterfaceType"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"modulesPath", "workflowsPath", "version", "buildTime", "groups"},
					ReturnNames: []string{"r"},
				},
				"WorkflowExecutor": {
					Name:        "WorkflowExecutor",
					NumIn:       4,
					NumOut:      1,
					ArgTypes:    []string{"string", "string", "map[string]*ast.InterfaceType", "[]string"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"command", "workflowPath", "config", "args"},
					ReturnNames: []string{"result"},
				},
			},
			"command": {
				"Test": {
					Name:        "Test",
					NumIn:       3,
					NumOut:      1,
					ArgTypes:    []string{"string", "map[string]*ast.InterfaceType", "map[string]*ast.InterfaceType"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"command", "config", "flags"},
					ReturnNames: []string{"r"},
				},
			},
			"help": {
				"Help": {
					Name:        "Help",
					NumIn:       3,
					NumOut:      1,
					ArgTypes:    []string{"string", "map[string]*ast.InterfaceType", "map[string]*ast.InterfaceType"},
					ReturnTypes: []string{"domain.FlowStepResult"},
					ArgNames:    []string{"command", "config", "flags"},
					ReturnNames: []string{"r"},
				},
			},
		},
	})
}
